version: '3.9'

services:
  bot:
    container_name: nure_bot
    build: ./
    depends_on:
      - database
    command: >
      bash -c '
      while !</dev/tcp/database/5432; do sleep 1; done;
      python main.py'
    volumes:
      - .:/src/app
    restart: always
    env_file:
      - .env

  database:
    container_name: nure_bot_db
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    ports:
      - ${POSTGRES_DB_HOST_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

volumes:
  postgres: