"""without link uni_groups

Revision ID: 0602bbcff84d
Revises: 85a5a266c88e
Create Date: 2025-10-14 10:39:59.536743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0602bbcff84d'
down_revision: Union[str, None] = '85a5a266c88e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('university_group_id', sa.Integer(), nullable=False))
    op.drop_constraint('subjects_brief_key', 'subjects', type_='unique')
    op.drop_constraint('subjects_name_key', 'subjects', type_='unique')
    op.create_foreign_key(None, 'subjects', 'university_groups', ['university_group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.create_unique_constraint('subjects_name_key', 'subjects', ['name'])
    op.create_unique_constraint('subjects_brief_key', 'subjects', ['brief'])
    op.drop_column('subjects', 'university_group_id')
    # ### end Alembic commands ###
