"""with update index link 2

Revision ID: 1e6dea72f3a1
Revises: bcb8546d9e04
Create Date: 2025-10-14 11:25:07.833067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e6dea72f3a1'
down_revision: Union[str, None] = 'bcb8546d9e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_link_per_owner', table_name='class_links')
    op.create_index('ix_links_per_group_subject_type', 'class_links', ['university_group_id', 'subject_id', 'class_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_links_per_group_subject_type', table_name='class_links')
    op.create_index('ix_unique_link_per_owner', 'class_links', ['university_group_id', 'subject_id', 'class_type'], unique=False)
    # ### end Alembic commands ###
