"""new db

Revision ID: 4f0db43f8642
Revises: 
Create Date: 2025-10-13 19:33:55.362459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f0db43f8642'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_links', sa.Column('class_type', sa.String(), nullable=True))
    op.add_column('class_links', sa.Column('owner_user_id', sa.Integer(), nullable=False))
    op.add_column('class_links', sa.Column('owner_username', sa.String(), nullable=True))
    op.create_index('ix_unique_link_per_owner', 'class_links', ['university_group_id', 'subject_id', 'class_type', 'owner_user_id'], unique=True)
    op.drop_column('class_links', 'link_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_links', sa.Column('link_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index('ix_unique_link_per_owner', table_name='class_links')
    op.drop_column('class_links', 'owner_username')
    op.drop_column('class_links', 'owner_user_id')
    op.drop_column('class_links', 'class_type')
    # ### end Alembic commands ###
