"""without username

Revision ID: 715b45eff509
Revises: 4f0db43f8642
Create Date: 2025-10-14 00:34:10.813080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '715b45eff509'
down_revision: Union[str, None] = '4f0db43f8642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class_links', 'owner_username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_links', sa.Column('owner_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
