"""without groups_subjects

Revision ID: 85a5a266c88e
Revises: f82604149294
Create Date: 2025-10-14 10:05:05.657897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a5a266c88e'
down_revision: Union[str, None] = 'f82604149294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_uni_group_subject_unique', table_name='group_subjects')
    op.drop_table('group_subjects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_subjects',
    sa.Column('university_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name='group_subjects_subject_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['university_group_id'], ['university_groups.id'], name='group_subjects_university_group_id_fkey', ondelete='CASCADE')
    )
    op.create_index('ix_uni_group_subject_unique', 'group_subjects', ['university_group_id', 'subject_id'], unique=False)
    # ### end Alembic commands ###
