"""without username with name

Revision ID: 8883fa08b1fa
Revises: 715b45eff509
Create Date: 2025-10-14 00:36:01.050112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8883fa08b1fa'
down_revision: Union[str, None] = '715b45eff509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_links', sa.Column('name_link', sa.String(), nullable=True))
    op.drop_column('class_links', 'attendance_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_links', sa.Column('attendance_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('class_links', 'name_link')
    # ### end Alembic commands ###
