"""add university_group_id to subjects

Revision ID: a95862d2a35b
Revises: 0602bbcff84d
Create Date: 2025-10-14 11:01:56.061166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95862d2a35b'
down_revision: Union[str, None] = '0602bbcff84d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_uni_group_subject_unique', table_name='group_subjects')
    op.drop_table('group_subjects')
    op.add_column('subjects', sa.Column('university_group_id', sa.Integer(), nullable=True))
    op.drop_constraint('subjects_brief_key', 'subjects', type_='unique')
    op.drop_constraint('subjects_name_key', 'subjects', type_='unique')
    op.create_foreign_key(None, 'subjects', 'university_groups', ['university_group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.create_unique_constraint('subjects_name_key', 'subjects', ['name'])
    op.create_unique_constraint('subjects_brief_key', 'subjects', ['brief'])
    op.drop_column('subjects', 'university_group_id')
    op.create_table('group_subjects',
    sa.Column('university_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name='group_subjects_subject_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['university_group_id'], ['university_groups.id'], name='group_subjects_university_group_id_fkey', ondelete='CASCADE')
    )
    op.create_index('ix_uni_group_subject_unique', 'group_subjects', ['university_group_id', 'subject_id'], unique=False)
    # ### end Alembic commands ###
