"""with update index link

Revision ID: bcb8546d9e04
Revises: a95862d2a35b
Create Date: 2025-10-14 11:21:09.056954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcb8546d9e04'
down_revision: Union[str, None] = 'a95862d2a35b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_link_per_owner', table_name='class_links')
    op.create_index('ix_unique_link_per_owner', 'class_links', ['university_group_id', 'subject_id', 'class_type'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_link_per_owner', table_name='class_links')
    op.create_index('ix_unique_link_per_owner', 'class_links', ['university_group_id', 'subject_id', 'class_type', 'owner_user_id'], unique=False)
    # ### end Alembic commands ###
