"""without groups_subjects

Revision ID: f82604149294
Revises: 8883fa08b1fa
Create Date: 2025-10-14 10:04:22.104413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82604149294'
down_revision: Union[str, None] = '8883fa08b1fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_classes', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_index('ix_subject_id', 'schedule_classes', ['subject_id'], unique=False)
    op.create_foreign_key(None, 'schedule_classes', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule_classes', type_='foreignkey')
    op.drop_index('ix_subject_id', table_name='schedule_classes')
    op.drop_column('schedule_classes', 'subject_id')
    # ### end Alembic commands ###
